{% set lab = "jupyterlab >=3.4.7,<4.0.0a0" %}
{% set version = "0.1.8" %}

package:
  name: jupyterlab-ui-profiler
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-ui-profiler/jupyterlab_ui_profiler-{{ version }}.tar.gz
  sha256: a05fb218d09d59e4e5bc8b8401f6aaff0c0c9a71686680dc8793a2d66a908519

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - {{ lab }}
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - jupyter_server >=1.6,<3
  run_constrained:
    - {{ lab }}

test:
  imports:
    - jupyterlab_ui_profiler
  commands:
    - pip check
    # list
    - jupyter labextension list
    - jupyter server extension list
    - jupyter serverextension list
    # write to file
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    - jupyter serverextension list 1>serverextensions 2>&1
    # check
    - grep -iE "@jupyterlab/ui-profiler.*v{{ version }}.*OK" labextensions
    - grep -iE "jupyterlab_ui_profiler.*{{ version }}.*OK" server_extensions
    - grep -iE "jupyterlab_ui_profiler.*{{ version }}.*OK" serverextensions
  requires:
    - {{ lab }}
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyterlab/ui-profiler
  summary: JupyterLab extension for profiling UI performance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_ui_profiler/labextension/static/third-party-licenses.json
  doc_url: https://ui-profiler.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
